QUEUE_LABELS: list[str] = list("ABCDEFGHJK")
MAX_QUEUES: int = len(QUEUE_LABELS)
DEFAULT_QUEUE: str = "A"

ROOM_ID_ALPHABET: str = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
ROOM_ID_LENGTH: int = 6
QUEUE_CODE_LENGTH: int = 4

IDENTITY_TOKEN_BYTES: int = 16
JTI_BYTES: int = 8
INVITE_TOKEN_BYTES: int = 24
