from contextlib import AbstractAsyncContextManager
from datetime import datetime
from typing import Protocol

from src.domain.entities import Queue, Room, Ticket, TicketRecord


class RoomRepository(Protocol):
    async def save(self, room: Room) -> None: ...
    async def load(self, room_id: str) -> Room | None: ...
    async def close(self, room_id: str) -> None: ...


class QueueRepository(Protocol):
    async def save(self, queue: Queue) -> None: ...
    async def load(self, room_id: str, label: str) -> Queue | None: ...
    async def load_all(self, room_id: str) -> list[Queue]: ...
    async def delete(self, room_id: str, label: str) -> None: ...
    async def room_exists(self, room_id: str) -> bool: ...
    async def get_owner(self, room_id: str) -> str | None: ...
    async def set_owner(self, room_id: str, user_id: str) -> None: ...
    async def delete_all(self, room_id: str) -> None: ...
    async def get_avg_serve(self, room_id: str) -> int | None: ...
    async def update_avg_serve(self, room_id: str, serve_seconds: int) -> None: ...
    def lock(self, room_id: str) -> AbstractAsyncContextManager[None]:
        """Эксклюзивная блокировка на комнату для атомарного read-modify-write."""
        ...


class TicketRepository(Protocol):
    async def save(self, ticket: Ticket) -> None: ...
    async def mark_called(self, room_id: str, queue_label: str, num: str, at: datetime) -> None: ...
    async def mark_completed(
        self, room_id: str, queue_label: str, num: str, at: datetime
    ) -> None: ...
    async def load_history(self, room_id: str) -> list[TicketRecord]: ...


class EventPublisher(Protocol):
    async def publish(self, room_id: str, payload: dict) -> None: ...
    async def connect(self, room_id: str, websocket: object, user_id: str) -> None: ...
    def disconnect(self, room_id: str, websocket: object) -> None: ...
